In [1]:
#Импортируйте библиотеку NumPy
import numpy as np

In [ ]:
#Создайте массив из 10 нулей
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Создать массив из 10 единиц
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Создать массив из 10 пятерок
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#Создать массив из целых чисел от 10 до 50
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#Создать массив из четных чисел от 10 до 50
a=np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#Создать матрицу 3х3 с числами от 0 до 8
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Создать единичную матрицу 3x3
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Используйте NumPy для генерации случайного числа от 0 до 1
a=np.random.rand(1)
print(a)

[0.54681449]


In [2]:
#Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
a=np.random.rand(25)
print(a)

[0.09854769 0.1169475  0.752439   0.32104933 0.2401145  0.46063397
 0.47794473 0.56988387 0.81249156 0.15148367 0.63650992 0.49808594
 0.00414056 0.5798338  0.98320025 0.37259779 0.11448264 0.6656358
 0.71734537 0.64398562 0.80300476 0.35983432 0.11045624 0.31310648
 0.34819366]


In [2]:
#Создайте следующую матрицу используя функции библиотеки NumPy:
a=np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(a)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [8]:
#Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!). Эта матрица будет использоваться в последующих задачах
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
#Необходимо написать код который вернет следующую матрицуиз стартовой
print(mat[2:, 1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [15]:
#Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l.
a= mat[mat == 20]
print(a)

[20]


In [18]:
#Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
print(mat[0:3, 1]. reshape (3,1))

[[ 2]
 [ 7]
 [12]]


In [20]:
#Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
print(mat [4:] )

[[21 22 23 24 25]]


In [21]:
#Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
print(mat [3:] )

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [22]:
#Получить сумму всех значений в стартовой матрице mat
print(mat.sum() )

325


In [23]:
#Получить стандартное отклонение в стартовой матрице mat
print(mat.std() )

7.211102550927978


In [24]:
#Получить сумму значений в колонках в стартовой матрице mat
print(mat.sum(axis=0) )

[55 60 65 70 75]
